---
title: "빅데이터 분석 시각화 포폴 #1"
author: "김도혜"
date: "2019년 3월 14일"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(gridExtra)

mpg = as.data.frame(ggplot2::mpg)
midwest = as.data.frame(ggplot2::midwest)

# save(data, file="data/data.rda")
load("data/data.rda")
```


## 1.
#### mpg데이터에서 연도별 배기량에 따른 도시/고속도로 연비를 꺽은선으로 그리시오. (단, 2008년은 굵은 선으로 표현하시오)


```{r}
mpg = mpg %>% group_by(year,displ) %>% 
  summarise(cty = mean(cty), hwy = mean(hwy))
head(mpg)

mpg_1999 = mpg[mpg$year == 1999, ]
mpg_2008 = mpg[mpg$year == 2008, ]

ggplot() + 
  geom_line(data = mpg_1999, aes(x=displ, y=cty, color='1999 cty')) + 
  geom_line(data = mpg_1999, aes(x=displ, y=hwy, color='1999 hwy')) +
  geom_line(data = mpg_2008, aes(x=displ, y=cty, color='2008 cty'), size=2) +
  geom_line(data = mpg_2008, aes(x=displ, y=hwy, color='2008 hwy'), size=2) +
  xlab("배기량(cc)") +
  ylab("연비(M/h)") +
  labs(shape="year", title = '도시/고속도로 연비', subtitle = '(굵은 선은 2008년)')+
  scale_color_discrete(name="year")
```


## 2.
#### data(성적.csv) 데이터에서 국어 성적이 80점 이상인 학생들의 수를 성비가 보이도록 학급별로 막대그래프를 그리시오.


```{r}
stukor = data[data$kor>=80,]
head(data)
head(stukor)

ggplot(stukor, aes(cls)) +
  geom_bar(aes(fill=gen),
           width=0.5) +
  scale_fill_discrete(name="성별") +
  labs(title='국어 우수 학생', subtitle='80점 이상') + 
  xlab("학급") + ylab('학생수')

```


## 3.
#### 국어 성적이 95점 이상인 학생들의 점수별 밀도그래프를 그리시오.


```{r}
stukorA = data[data$kor>=95,]
head(stukorA)

ggplot(stukorA, aes(kor)) +
  geom_density(aes(fill=factor(cls)), alpha=0.4) +
  scale_fill_discrete(name="반") +
  labs(title='반별 국어 우수 학생', subtitle='국어 성적 A+') + 
  xlab("성적") + ylab('밀도')

```


## 4.
#### midwest데이터에서 전체인구와 아시아계 인구의 관계를 알아보기 위한 그래프를 그리시오. (단, 전체인구는 50만명 이하, 아시아계인구는 1만명 이하만 표시되게)


```{r}
asiatot = midwest %>% filter(poptotal <= 500000 && popasian <= 10000) %>% select(state,poptotal, popasian)
head(asiatot)

graph_1 = ggplot(asiatot) +
  geom_point(aes(x=poptotal, y=popasian), color="blue", alpha=0.3) +
    xlab("아시아 인구") +
    ylab("전체 인구") +
    labs(title = '아시아 인구 분포') 

graph_2 = ggplot(asiatot) +
  geom_point(aes(x=state, y=poptotal, color="전체 인구"),alpha=0.3) +
  geom_point(aes(x=state, y=popasian, color="아시아 인구"),alpha=0.3) +
  xlab("주(state)") +
  ylab("전체 인구") +
  scale_color_discrete(name="인구") +
  labs(title = '주별 아시아 인구 분포') 

grid.arrange(graph_1, graph_2, ncol=1)
```

